#!/usr/bin/ruby 

require 'rubygems'
require 'oyster'
require 'fileutils'

spec = Oyster.spec do
  name  'init-project create initial project files for your ruby project'

  description <<-EOS
   Simple application that creates project files for a Ruby project
   Creates the following project sructure:

        projectname/
         bin/
           projectname
         lib/
           projectname/
           projectname.rb    # will be responsible for requiring the source files in the lib/projectname dir
         features/
           step_definitions/
           support/
             env.rb          # will be responsible for requiring the lib/projectname.rb
         spec/
           projectname/
           spec_helper.rb    # will be responsible for requiring the lib/projectname.rb
  EOS

  synopsis <<-EOS
    myprogram [options] --option FILE
  EOS

  string :name, :desc => 'Name of the project'

  author 'Tumas Bajoras <hanniph@gmail.com>'

  copyright <<-EOS
    (c) 2010 Tumas Bajoras. This program is free software, distributed under
    the MIT license. You are free to use it for whatever purpose you see fit.
  EOS
end

class InitProject
  include FileUtils

  VERSION = "0.0.2"

  def initialize(spec)
    @spec = spec
  end

  def parsed_options?
    @opts = @spec.parse
    unless @opts[:name]
      @name = "default"
    else
      @name = @opts[:name]
    end
    true
  end

  def run
    if parsed_options? 
      # program logic
      mkdir @name
      cd @name do
        mkdir %w{ bin features lib spec }

        cd 'bin' do 
          File.open(@name, 'w', 0777) do |file|
            file << <<-eos
#!/usr/bin/ruby
$: << File.join(File.dirname(__FILE__), "/../lib")
            eos
          end
        end

        cd 'features' do
          mkdir %w{ step_definitions support }
          cd 'step_definitions' do 
            touch "#{@name.downcase}.rb"
          end

          cd 'support' do
            File.open('env.rb', 'w') do |file|
              file << <<-eos
#!/usr/bin/ruby
$: << File.join(File.dirname(__FILE__), "/../../lib")

require '#{@name.downcase}'
              eos
            end
          end
        end

        cd 'lib' do
          mkdir @name
          touch "#{@name.downcase}.rb"
        end

        cd 'spec' do
          mkdir @name
          File.open('spec_helper.rb', 'w') do |file|
            file << <<-eos
$: << File.join(File.dirname(__FILE__), "/../lib" )

require 'spec'
require '#{@name.downcase}'
            eos
          end
        end
      end

    end
  end
end

InitProject.new(spec).run
